package euterpea.midi

import euterpea.Music.InstrumentName
import InstrumentName._
import utils.Enum

object GeneralMidi
  def fromGM(i: Int): InstrumentName =
    if (i >= 0 && i <= 127)
      Enum[InstrumentName].toEnum(i)
    else
      sys.error(s"fromGM: $i is not a valid General Midi Number")

  def toGM(iName: InstrumentName): Int =
    iName match
    case Percussion => 0
    case CustomInstrument(_) => 0
    case i => Enum[InstrumentName].fromEnum(i)

  given Enum[InstrumentName]
    def toEnum(i: Int): InstrumentName =
        i match 
        case 0 => AcousticGrandPiano
        case 1 => BrightAcousticPiano
        case 2 => ElectricGrandPiano
        case 3 => HonkyTonkPiano
        case 4 => RhodesPiano
        case 5 => ChorusedPiano
        case 6 => Harpsichord
        case 7 => Clavinet
        case 8 => Celesta
        case 9 => Glockenspiel
        case 10 => MusicBox
        case 11 => Vibraphone
        case 12 => Marimba
        case 13 => Xylophone
        case 14 => TubularBells
        case 15 => Dulcimer
        case 16 => HammondOrgan
        case 17 => PercussiveOrgan
        case 18 => RockOrgan
        case 19 => ChurchOrgan
        case 20 => ReedOrgan
        case 21 => Accordion
        case 22 => Harmonica
        case 23 => TangoAccordion
        case 24 => AcousticGuitarNylon
        case 25 => AcousticGuitarSteel
        case 26 => ElectricGuitarJazz
        case 27 => ElectricGuitarClean
        case 28 => ElectricGuitarMuted
        case 29 => OverdrivenGuitar
        case 30 => DistortionGuitar
        case 31 => GuitarHarmonics
        case 32 => AcousticBass
        case 33 => ElectricBassFingered
        case 34 => ElectricBassPicked
        case 35 => FretlessBass
        case 36 => SlapBass1
        case 37 => SlapBass2
        case 38 => SynthBass1
        case 39 => SynthBass2
        case 40 => Violin
        case 41 => Viola
        case 42 => Cello
        case 43 => Contrabass
        case 44 => TremoloStrings
        case 45 => PizzicatoStrings
        case 46 => OrchestralHarp
        case 47 => Timpani
        case 48 => StringEnsemble1
        case 49 => StringEnsemble2
        case 50 => SynthStrings1
        case 51 => SynthStrings2
        case 52 => ChoirAahs
        case 53 => VoiceOohs
        case 54 => SynthVoice
        case 55 => OrchestraHit
        case 56 => Trumpet
        case 57 => Trombone
        case 58 => Tuba
        case 59 => MutedTrumpet
        case 60 => FrenchHorn
        case 61 => BrassSection
        case 62 => SynthBrass1
        case 63 => SynthBrass2
        case 64 => SopranoSax
        case 65 => AltoSax
        case 66 => TenorSax
        case 67 => BaritoneSax
        case 68 => Oboe
        case 69 => EnglishHorn
        case 70 => Bassoon
        case 71 => Clarinet
        case 72 => Piccolo
        case 73 => Flute
        case 74 => Recorder
        case 75 => PanFlute
        case 76 => BlownBottle
        case 77 => Shakuhachi
        case 78 => Whistle
        case 79 => Ocarina
        case 80 => Lead1Square
        case 81 => Lead2Sawtooth
        case 82 => Lead3Calliope
        case 83 => Lead4Chiff
        case 84 => Lead5Charang
        case 85 => Lead6Voice
        case 86 => Lead7Fifths
        case 87 => Lead8BassLead
        case 88 => Pad1NewAge
        case 89 => Pad2Warm
        case 90 => Pad3Polysynth
        case 91 => Pad4Choir
        case 92 => Pad5Bowed
        case 93 => Pad6Metallic
        case 94 => Pad7Halo
        case 95 => Pad8Sweep
        case 96 => FX1Train
        case 97 => FX2Soundtrack
        case 98 => FX3Crystal
        case 99 => FX4Atmosphere
        case 100 => FX5Brightness
        case 101 => FX6Goblins
        case 102 => FX7Echoes
        case 103 => FX8SciFi
        case 104 => Sitar
        case 105 => Banjo
        case 106 => Shamisen
        case 107 => Koto
        case 108 => Kalimba
        case 109 => Bagpipe
        case 110 => Fiddle
        case 111 => Shanai
        case 112 => TinkleBell
        case 113 => Agogo
        case 114 => SteelDrums
        case 115 => Woodblock
        case 116 => TaikoDrum
        case 117 => MelodicDrum
        case 118 => SynthDrum
        case 119 => ReverseCymbal
        case 120 => GuitarFretNoise
        case 121 => BreathNoise
        case 122 => Seashore
        case 123 => BirdTweet
        case 124 => TelephoneRing
        case 125 => Helicopter
        case 126 => Applause
        case 127 => Gunshot
        case n => sys.error(s"toEnum($n) is not implemented for InstrumentName")
    end toEnum

    def fromEnum(a: InstrumentName): Int =
        a match
        case AcousticGrandPiano => 0
        case BrightAcousticPiano => 1
        case ElectricGrandPiano => 2
        case HonkyTonkPiano => 3
        case RhodesPiano => 4
        case ChorusedPiano => 5
        case Harpsichord => 6
        case Clavinet => 7
        case Celesta => 8
        case Glockenspiel => 9
        case MusicBox => 10
        case Vibraphone => 11
        case Marimba => 12
        case Xylophone => 13
        case TubularBells => 14
        case Dulcimer => 15
        case HammondOrgan => 16
        case PercussiveOrgan => 17
        case RockOrgan => 18
        case ChurchOrgan => 19
        case ReedOrgan => 20
        case Accordion => 21
        case Harmonica => 22
        case TangoAccordion => 23
        case AcousticGuitarNylon => 24
        case AcousticGuitarSteel => 25
        case ElectricGuitarJazz => 26
        case ElectricGuitarClean => 27
        case ElectricGuitarMuted => 28
        case OverdrivenGuitar => 29
        case DistortionGuitar => 30
        case GuitarHarmonics => 31
        case AcousticBass => 32
        case ElectricBassFingered => 33
        case ElectricBassPicked => 34
        case FretlessBass => 35
        case SlapBass1 => 36
        case SlapBass2 => 37
        case SynthBass1 => 38
        case SynthBass2 => 39
        case Violin => 40
        case Viola => 41
        case Cello => 42
        case Contrabass => 43
        case TremoloStrings => 44
        case PizzicatoStrings => 45
        case OrchestralHarp => 46
        case Timpani => 47
        case StringEnsemble1 => 48
        case StringEnsemble2 => 49
        case SynthStrings1 => 50
        case SynthStrings2 => 51
        case ChoirAahs => 52
        case VoiceOohs => 53
        case SynthVoice => 54
        case OrchestraHit => 55
        case Trumpet => 56
        case Trombone => 57
        case Tuba => 58
        case MutedTrumpet => 59
        case FrenchHorn => 60
        case BrassSection => 61
        case SynthBrass1 => 62
        case SynthBrass2 => 63
        case SopranoSax => 64
        case AltoSax => 65
        case TenorSax => 66
        case BaritoneSax => 67
        case Oboe => 68
        case EnglishHorn => 69
        case Bassoon => 70
        case Clarinet => 71
        case Piccolo => 72
        case Flute => 73
        case Recorder => 74
        case PanFlute => 75
        case BlownBottle => 76
        case Shakuhachi => 77
        case Whistle => 78
        case Ocarina => 79
        case Lead1Square => 80
        case Lead2Sawtooth => 81
        case Lead3Calliope => 82
        case Lead4Chiff => 83
        case Lead5Charang => 84
        case Lead6Voice => 85
        case Lead7Fifths => 86
        case Lead8BassLead => 87
        case Pad1NewAge => 88
        case Pad2Warm => 89
        case Pad3Polysynth => 90
        case Pad4Choir => 91
        case Pad5Bowed => 92
        case Pad6Metallic => 93
        case Pad7Halo => 94
        case Pad8Sweep => 95
        case FX1Train => 96
        case FX2Soundtrack => 97
        case FX3Crystal => 98
        case FX4Atmosphere => 99
        case FX5Brightness => 100
        case FX6Goblins => 101
        case FX7Echoes => 102
        case FX8SciFi => 103
        case Sitar => 104
        case Banjo => 105
        case Shamisen => 106
        case Koto => 107
        case Kalimba => 108
        case Bagpipe => 109
        case Fiddle => 110
        case Shanai => 111
        case TinkleBell => 112
        case Agogo => 113
        case SteelDrums => 114
        case Woodblock => 115
        case TaikoDrum => 116
        case MelodicDrum => 117
        case SynthDrum => 118
        case ReverseCymbal => 119
        case GuitarFretNoise => 120
        case BreathNoise => 121
        case Seashore => 122
        case BirdTweet => 123
        case TelephoneRing => 124
        case Helicopter => 125
        case Applause => 126
        case Gunshot => 127
        case i => sys.error(s"fromEnum($i) is not implemented")
    end fromEnum

    def enumFrom(i: InstrumentName): Seq[InstrumentName] =
      ???
end GeneralMidi